version: '3'

services:
  flask_app:
    image: python:3.11-slim
    container_name: jenkins_fitness_app
    working_dir: /app
    volumes:
      - /opt/jenkins/workspace/flask-pipeline:/app
    ports:
      - "5001:5000"
    command: >
      sh -c "pip install -r requirements.txt --quiet &&
             python application.py"
    restart: always